### ISSUE TITLE
error in def-view

### ISSUE THREAD

**Issue by stumitchell** [flexsurfer/re-frisk#2]
I am getting this error with your def-view macro
```
(def-view app-footer
     ^--- Don't know how to create ISeq from: clojure.lang.Keyword
```

**Comment by flexsurfer** [comment]
Sorry, i don't know why i didn't see this issue. can you provide more info? code of app-footer ?

**Comment by stumitchell** [comment]
I think I was using an older version :-/ that error doesn't happen now thanks
