### ISSUE TITLE
Debugger doesn't work in electron

### ISSUE THREAD

**Issue by IsaacKhor** [flexsurfer/re-frisk#23]
The debugger window is just completely blank when it is triggered from electron (from the renderer process). Devtools in the window show that there's nothing; it's completely blank.

**Comment by flexsurfer** [comment]
thank you, I've never worked with the electron, but if this is a desktop app, so there should the different way to open separate window I think

**Comment by flexsurfer** [comment]
@IsaacKhor I've looked electron, and it's not easy to implement re-frisk into electron because different render processes in opened windows

**Comment by flexsurfer** [comment]
in 0.4.4
