### ISSUE TITLE
Shorten fully qualified keywords that belong to app's namespace

### ISSUE THREAD

**Issue by alexander-yakushev** [flexsurfer/re-frisk#25]
I use namespace-qualified keywords everywhere in my `app-db`, and when re-frisk renders them completely, I have to make its window width very wide to be able to see anything. Do you think it would be possible to treat this somehow? I see one possible solution: allow to specify a prefix of your app when initializing re-frisk, like `(enable-re-frisk! {:common-ns-prefix "com.example.myapp"})`, so that later the keywords are rendered like `:.core/foo`.

**Comment by flexsurfer** [comment]
hi, i have the same thing in my project, but i can't find the good solution, i should think about it again

**Comment by occamin** [comment]
I've been using Cursive recently and I've found their truncated namespace style pretty convenient. E.g. `clojure.tools.nrepl.middleware.interruptible-eval` gets rendered as `c.t.n.m.interruptible-eval`.

**Comment by flexsurfer** [comment]
0.5.0
