### ISSUE TITLE
Free text search

### ISSUE THREAD

**Issue by lsnape** [flexsurfer/re-frisk#26]
Sometimes finding data buried in our ever growing app-db can be tedious. I think it would be great if we could filter the app state using free text search. We had something very similar in our app before we swapped in favour of re-frisk, and we found it very useful.

Happy to discuss further and/or submit a PR :)

Luke

**Comment by flexsurfer** [comment]
Hi Luke, yes i have this in my plans, but i don't have time, i'm open for PR :) Thanks

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by flexsurfer** [comment]
https://github.com/flexsurfer/re-frisk-shell/issues/4

**Comment by flexsurfer** [comment]
0.5.3
