### ISSUE TITLE
Don't use (.alert) when window is refreshed

### ISSUE THREAD

**Issue by timgilbert** [flexsurfer/re-frisk#28]
It would be nice if the external-window version of re-frisk didn't fire a `window.alert()` when the main window is refreshed - it winds up stealing focus and making the user click a button right when the user is trying to interact with the main window. I'd suggest maybe a `(.warn js/console)` instead, or possibly changing the external window so that it displays a prominent message telling the user that the debugger is not connected to the main app.

I could probably slap together a PR for this in a few days if you agree. Thanks!

**Comment by flexsurfer** [comment]
hi. thank you, yes using an alert not a good idea, but a developer should know that re-frisk doesn't work anymore, maybe better show a message in div on top

**Comment by flexsurfer** [comment]
fixed in v1
