### ISSUE TITLE
Make side bar resizable

### ISSUE THREAD

**Issue by borkdude** [flexsurfer/re-frisk#31]
I can't read many of the event names because the side bar is too small in width.
![screenshot 2017-03-16 14 05 04](https://cloud.githubusercontent.com/assets/284934/23997467/bc66db08-0a51-11e7-9fc0-56912b97973d.png)

**Comment by flexsurfer** [comment]
yes, thank you for the issue, I'm always thought about ui refresh, all panels should be resizable, but i really don't have time for that :(

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by eliaskingston** [comment]
I've fixed this issue in re-frisk-shell rather than re-frisk. Can I submit a pull request to re-frisk-shell and still claim the bounty?

**Comment by flexsurfer** [comment]
@eliaskingston bounty works in the testnet, so bounty in test ETH, sorry for that

**Comment by jeluard** [comment]
@eliaskingston Do you mind creating your PR anyway? It would be nice to benefit from your work!

**Comment by eliaskingston** [comment]
Yes Julien, I'll get a PR submitted ASAP.

 


Sent: Saturday, May 13, 2017 at 8:46 AM

**Comment by flexsurfer** [comment]
0.5.0
