### ISSUE TITLE
lein re-frisk -> Could not find artifact org.clojure:clojure:jar:1.8.0

### ISSUE THREAD

**Issue by gnl** [flexsurfer/re-frisk#32]
```
% lein re-frisk
Could not find artifact org.clojure:clojure:jar:1.8.0
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
command failed with status: 1
```
I confirmed it's not a network issue, I could install a number of other dependencies no problem.

**Comment by flexsurfer** [comment]
hi, thank you for your report, looks like i need to add clojure 1.8 into lein project dependencies

**Comment by gnl** [comment]
I'm using re-natal / React Native if it's somehow relevant and really looking forward to making re-frisk work, it looks fantastic.

**Comment by flexsurfer** [comment]
@gnl yes, I'm working with re-natal using re-frisk, it's great experience, you can take a look re-natal settings here https://github.com/status-im/status-react/pull/858/files

**Comment by flexsurfer** [comment]
0.4.5

**Comment by gnl** [comment]
Working great now. And thanks for the config, it's even nicer now not having to manually run lein re-frisk.

**Comment by flexsurfer** [comment]
awesome, thanks for the feedback!
