### ISSUE TITLE
Use cljs preloads

### ISSUE THREAD

**Issue by piotr-yuxuan** [flexsurfer/re-frisk#33]
Hi :-) I use re-frisk on a daily basis and find it utmost useful (many thanks for sorted-app-db btw)

I've been thinking a tiny yet useful feature may be missing: 

https://github.com/clojure/clojurescript/wiki/Compiler-Options#preloads

It would be nice to have. Moreover preloads aren't included in advanced builds, which is on par with re-frisk readme advices.

It looks so very easy to do, I would volunteer to do it if you agree to.

**Comment by flexsurfer** [comment]
Hi @piotr-yuxuan, thank you for your feedback, I'm working alone on re-frisk and do not have feedback at all, maybe nobody besides me uses it, so glad to hear you find it useful, I really like your idea, and will be glad to see you as a contributor! thank you

**Comment by cmal** [comment]
As a newbie, I am looking forward to that. 😄

**Comment by piotr-yuxuan** [comment]
I gonna write this.

**Comment by flexsurfer** [comment]
0.5.0
