### ISSUE TITLE
Jump to state after a past event

### ISSUE THREAD

**Issue by willspecht** [flexsurfer/re-frisk#34]
Don't know if I'm just missing this functionality or if it's not implemented. I would like to set the state of my re-frame app back to a previous state by clicking on an event. I see the events on the left hand side but clicking on them doesn't change my current state. Is this possible or planed for future versions?

**Comment by flexsurfer** [comment]
Hey @willspecht it's possible but not planned, I'm open for PR

**Comment by occamin** [comment]
This was also one of my immediate thoughts since it would help understand the evolution of the state without eye-balling the :app-db. I might be interested in picking this up in the next couple of months as time allows

**Comment by flexsurfer** [comment]
https://github.com/flexsurfer/re-frisk/issues/42

**Comment by flexsurfer** [comment]
0.5.3
