### ISSUE TITLE
What is the reasonable way to only `require` re-frisk in development?

### ISSUE THREAD

**Issue by cmal** [flexsurfer/re-frisk#35]
I add this to dev/dependencies and `:require` it in `core.cljs`,
then I `lein uberjar`, it tells me `No such namespace: re-frisk.core`,
I want `re-frisk` not be used in production env when I `lein uberjar`,
how should I do?

Thanks.

**Comment by flexsurfer** [comment]
hey @cmal take a look here https://github.com/flexsurfer/re-frisk/issues/33

**Comment by cmal** [comment]
Thanks.
