### ISSUE TITLE
Metadata leak in re-frisk

### ISSUE THREAD

**Issue by astoeckley** [flexsurfer/re-frisk#38]
Not sure if this should be put here, but re-frisk is possible the culprit for this metadata leak:

https://github.com/Day8/re-frame/issues/365#issuecomment-315356432

Also, note the very large compile time introduced by re-frisk.

**Comment by flexsurfer** [comment]
yeah, thanks @astoeckley . it's because i'm using cljs.js https://github.com/flexsurfer/re-frisk-shell/blob/master/src/re_frisk_shell/core.cljs#L6, looks like it's better to do not include this by default

**Comment by astoeckley** [comment]
Thanks, do you know if this will be a quick fix? If not, I will remove re-frisk from my project until it is resolved.

**Comment by flexsurfer** [comment]
unfortunately it's not quick, so you can use 0.3.2 if you need re-frisk, or remove it

**Comment by astoeckley** [comment]
Was 0.3.2 before you made a big change to cause this particular issue? Anything else that is notably different in 0.3.2?

**Comment by flexsurfer** [comment]
yes, 0.3.2 has the same functionality, but without this cljs runtime compiler

**Comment by astoeckley** [comment]
Incidentally, perhaps the reason that my advanced compilation build with re-frisk takes 200 seconds is that somehow re-frisk is still entering the picture there, despite that the reframe template seems to be preventing that. cljs.js is not compatible with advanced optimizations.

**Comment by mike-thompson-day8** [comment]
We have stepped back to 0.3.2 also.  This is a pretty nasty trap.   Thanks for highlighting it @astoeckley

**Comment by flexsurfer** [comment]
@mike-thompson-day8 sorry for that, i'm working only with remote version, so i haven't seen this problem, and no one report the problem long time, i will fix this asap this weekend, i'm reworking UI atm, using re-com, but faced performance issues in safari, and bug with splitter,  could you give advice should i continue with re-com for re-frisk or better leave old UI for now? i know you don't recommend it for safari , thanks

**Comment by mike-thompson-day8** [comment]
I think it may be safest to stick with the old UI. 

re-com works really well for us,  but we're on Chrome.

**Comment by flexsurfer** [comment]
fixed in 0.5.0
