### ISSUE TITLE
Errors & incompatibility with re-frame-datatable

### ISSUE THREAD

**Issue by mmower** [flexsurfer/re-frisk#39]
Hi.

If I try and use re-frisk with re-frame-database then I get two errors (repeated) during enable-re-frisk!

It appears to relate to the re-frisk.help:47 somehow `k` is unexpectedly `""` or `nil`.

The re-frame-datatable code is doing some tricky subscribes so it could be that. But I didn't just want to patch in a test for `nil` and ignore the error.

m/

core.cljs:3782 re-frame: expected a vector, but got: null
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$4 @ core.cljs:3782
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$3 @ core.cljs:3777
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3771
cljs.core.apply.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3806
cljs$core$apply @ core.cljs:3797
re_frame.loggers.console.cljs$core$IFn$_invoke$arity$variadic @ loggers.cljc?rel=1503182097748:38
re_frame$loggers$console @ loggers.cljc?rel=1503182097748:35
re_frame$utils$first_in_vector @ utils.cljc?rel=1503182097936:24
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:81
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
re_frame.core.reg_sub.call.vec__45860 @ core.cljs?rel=1503182416807:234
re_frame$subs$subs_handler_fn__2 @ subs.cljc?rel=1503182098502:207
re_frame$subs$subs_handler_fn @ subs.cljc?rel=1503182098502:217
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:87
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
(anonymous) @ help.cljs?rel=1503182111802:47
(anonymous) @ core.cljs:4567
cljs.core.map.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4567
cljs.core.LazySeq.sval @ core.cljs:3308
cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 @ core.cljs:3362
cljs$core$seq @ core.cljs:1125
cljs.core.Cons.cljs$core$INext$_next$arity$1 @ core.cljs:3141
cljs$core$next @ core.cljs:1170
cljs.core.seq_reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2364
cljs.core.LazySeq.cljs$core$IReduce$_reduce$arity$3 @ core.cljs:3372
cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2431
cljs.core.into.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4842
cljs$core$into @ core.cljs:4834
re_frisk$help$re_frame_sub @ help.cljs?rel=1503182111802:46
(anonymous) @ help.cljs?rel=1503182111802:59
reagent.ratom.Reaction.cljs$core$IDeref$_deref$arity$1 @ ratom.cljs?rel=1503182091618:447
cljs$core$_deref @ core.cljs:588
cljs$core$deref @ core.cljs:1364
re_frisk$help$re_frame_handlers @ help.cljs?rel=1503182111802:61
re_frisk.core.enable_re_frisk_BANG_.cljs$core$IFn$_invoke$arity$variadic @ core.cljs?rel=1503182111856:30
re_frisk$core$enable_re_frisk_BANG_ @ core.cljs?rel=1503182111856:25
dtrh$core$dev_setup @ core.cljs?rel=1503182416902:34
dtrh$core$init @ core.cljs?rel=1503182416902:43
(anonymous) @ (index):17

followed by

core.cljs:3776 re-frame: no subscription handler registered for: "". Returning a nil subscription.
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$3 @ core.cljs:3776
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3771
cljs.core.apply.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3806
cljs$core$apply @ core.cljs:3797
re_frame.loggers.console.cljs$core$IFn$_invoke$arity$variadic @ loggers.cljc?rel=1503182097748:38
re_frame$loggers$console @ loggers.cljc?rel=1503182097748:35
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:86
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
re_frame.core.reg_sub.call.vec__45860 @ core.cljs?rel=1503182416807:234
re_frame$subs$subs_handler_fn__2 @ subs.cljc?rel=1503182098502:207
re_frame$subs$subs_handler_fn @ subs.cljc?rel=1503182098502:217
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:87
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
(anonymous) @ help.cljs?rel=1503182111802:47
(anonymous) @ core.cljs:4567
cljs.core.map.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4567
cljs.core.LazySeq.sval @ core.cljs:3308
cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 @ core.cljs:3362
cljs$core$seq @ core.cljs:1125
cljs.core.Cons.cljs$core$INext$_next$arity$1 @ core.cljs:3141
cljs$core$next @ core.cljs:1170
cljs.core.seq_reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2364
cljs.core.LazySeq.cljs$core$IReduce$_reduce$arity$3 @ core.cljs:3372
cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2431
cljs.core.into.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4842
cljs$core$into @ core.cljs:4834
re_frisk$help$re_frame_sub @ help.cljs?rel=1503182111802:46
(anonymous) @ help.cljs?rel=1503182111802:59
reagent.ratom.Reaction.cljs$core$IDeref$_deref$arity$1 @ ratom.cljs?rel=1503182091618:447
cljs$core$_deref @ core.cljs:588
cljs$core$deref @ core.cljs:1364
re_frisk$help$re_frame_handlers @ help.cljs?rel=1503182111802:61
re_frisk.core.enable_re_frisk_BANG_.cljs$core$IFn$_invoke$arity$variadic @ core.cljs?rel=1503182111856:30
re_frisk$core$enable_re_frisk_BANG_ @ core.cljs?rel=1503182111856:25
dtrh$core$dev_setup @ core.cljs?rel=1503182416902:34
dtrh$core$init @ core.cljs?rel=1503182416902:43
(anonymous) @ (index):17
core.cljs:3782 re-frame: expected a vector, but got: null
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$4 @ core.cljs:3782
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$3 @ core.cljs:3777
cljs.core.apply_to_simple.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3771
cljs.core.apply.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3806
cljs$core$apply @ core.cljs:3797
re_frame.loggers.console.cljs$core$IFn$_invoke$arity$variadic @ loggers.cljc?rel=1503182097748:38
re_frame$loggers$console @ loggers.cljc?rel=1503182097748:35
re_frame$utils$first_in_vector @ utils.cljc?rel=1503182097936:24
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:81
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
re_frame.core.reg_sub.call.vec__45848 @ core.cljs?rel=1503182416807:214
re_frame$subs$subs_handler_fn__2 @ subs.cljc?rel=1503182098502:207
re_frame$subs$subs_handler_fn @ subs.cljc?rel=1503182098502:217
re_frame.subs.subscribe.cljs$core$IFn$_invoke$arity$1 @ subs.cljc?rel=1503182098502:87
re_frame$subs$subscribe @ subs.cljc?rel=1503182098502:69
(anonymous) @ help.cljs?rel=1503182111802:47
(anonymous) @ core.cljs:4567
cljs.core.map.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4567
cljs.core.LazySeq.sval @ core.cljs:3308
cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 @ core.cljs:3362
cljs$core$seq @ core.cljs:1125
cljs.core.Cons.cljs$core$INext$_next$arity$1 @ core.cljs:3141
cljs$core$next @ core.cljs:1170
cljs.core.seq_reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2364
cljs.core.LazySeq.cljs$core$IReduce$_reduce$arity$3 @ core.cljs:3372
cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 @ core.cljs:2431
cljs.core.into.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4842
cljs$core$into @ core.cljs:4834
re_frisk$help$re_frame_sub @ help.cljs?rel=1503182111802:46
(anonymous) @ help.cljs?rel=1503182111802:59
reagent.ratom.Reaction.cljs$core$IDeref$_deref$arity$1 @ ratom.cljs?rel=1503182091618:447
cljs$core$_deref @ core.cljs:588
cljs$core$deref @ core.cljs:1364
re_frisk$help$re_frame_handlers @ help.cljs?rel=1503182111802:61
re_frisk.core.enable_re_frisk_BANG_.cljs$core$IFn$_invoke$arity$variadic @ core.cljs?rel=1503182111856:30
re_frisk$core$enable_re_frisk_BANG_ @ core.cljs?rel=1503182111856:25
dtrh$core$dev_setup @ core.cljs?rel=1503182416902:34
dtrh$core$init @ core.cljs?rel=1503182416902:43
(anonymous) @ (index):17

**Comment by flexsurfer** [comment]
should be fixed in 0.5.0
