### ISSUE TITLE
Show app-db changes which was made by selected event 

### ISSUE THREAD

**Issue by flexsurfer** [flexsurfer/re-frisk#42]
In current implementation if you click on event in the left panel list, you can see event vector in separate panel, it would be good also to see the app-db data which was changed by this event, for example, if we had app-db 
```
{:a 1 :b 3}
```
and selected event changed :b key on 4 we should see
```
{:b 4}
```
so it should be a difference of app-db before this event and after

This task should be done for both re-frisk and re-frisk-remote (https://github.com/flexsurfer/re-frisk-remote/issues/4)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x99d4d83bc88d1b40466e87cb8df23e145a1a8e1597542d4b1d9372f9b6623662](https://etherscan.io/tx/0x99d4d83bc88d1b40466e87cb8df23e145a1a8e1597542d4b1d9372f9b6623662)

**Comment by dottedmag** [comment]
I'll take a stab at implementing this one.

**Comment by dottedmag** [comment]
Also re-frisk-remote#5 – I need advice on how to avoid code duplication though.
