### ISSUE TITLE
Monorepo for re-frisk-*

### ISSUE THREAD

**Issue by dottedmag** [flexsurfer/re-frisk#44]
`re-frisk` would be easier to develop if it weren't scattered through 4 (5 if one counts a test application) repositories.

Maybe a monorepo would be more convenient? `lein-re-frisk` already contains two projects.

**Comment by jeaye** [comment]
Yeah, I certainly agree with this. It'd be easier for folks to star the one re-frisk repo as well, which would more accurately reflect how much people fucking love this project. By the way, I fucking love this project.

**Comment by flexsurfer** [comment]
fixed in v1
