### ISSUE TITLE
Failed to compile `re-frisk-remote` with Figwheel

### ISSUE THREAD

**Issue by lksilva** [flexsurfer/re-frisk#52]
I try to add `re-frisk-remote` to my re-frame project following [re-frisk guide](https://github.com/flexsurfer/re-frisk#react-native-electron-or-web-applications) but for any reason isn't working, can someone help me to resolve that or re-frisk works just with `shadow clsj`?

```clojure
#dev.cljs.edn
...
:preloads        [devtools.preload
                        re-frisk-remote.preload]
...
```

```clojure
#project.clj
...
  :profiles {:dev    {:dependencies [[com.bhauman/figwheel-main "0.2.3"]
                                     [re-frisk-remote "1.2.0"]]
...
```

When starting the application we got this error 
<img width="810" alt="Screen Shot 2020-04-28 at 12 46 33" src="https://user-images.githubusercontent.com/8785700/80508382-5b462700-894e-11ea-8d4d-9b78b9c7fc2a.png">

We try to run `re-frisk` but isn't work as well

**Comment by flexsurfer** [comment]
hey @lksilva , it should work with Figwheel, it works not only with shadow, it seems like a problem in the dependencies, one of the libraries for re-frisk-remote uses `com.taoensso/encore 2.84.2` for some reason your project uses an older version probably

**Comment by lksilva** [comment]
Thanks for your reply but it's a little bit weird because we don't use this library defined on `project.clj` but I will try to put this one there

**Comment by flexsurfer** [comment]
@lksilva yes sometimes it's weird, probably cache or dependencies conflict, btw why re-frisk doesn't work for you?

**Comment by lksilva** [comment]
Probably cache dependencies as your suggest, I forced re-frisk-remote version to my project and that worksd =)
