### ISSUE TITLE
Better support for apps with lots of events

### ISSUE THREAD

**Issue by Deraen** [flexsurfer/re-frisk#58]
I'm working on a app where we receive WS event every 200 ms and these are handled in a re-frame event handler.

This pretty much breaks the Re-frisk event list, as it will have some many events it is impossible to navigate.

Re-frisk will also get quite slow when the event list grows.

In this case, I'd be happy to set up filter to skip these events. Not sure if this is possible to implement in Re-frisk or would this need support in Re-frame tracing?

Not sure if re-frisk keeps track of the app-db history, but if so, that will also probably grow quite big if old versions aren't dropped at some point.

**Comment by flexsurfer** [comment]
hey @Deraen , yeah with 200 ms events re-frisk will be pretty slow and useless, the simplest solution would be to implement `:ignore-events []` option in `enable` function, something like `(re-frisk/enable {:ignore-events [:event-name1 :event-name2]})` , will this work for you? or you would prefer to have it in the UI ?

> Not sure if re-frisk keeps track of the app-db history

it doesn't keep app-db history, only changes in each event

**Comment by Deraen** [comment]
I think option in `enable` function makes more sense here. This should be enabled for all users, so requiring everyone to configure this in UI isn't optiomal.

**Comment by flexsurfer** [comment]
@Deraen you can try v. 1.3.5 
`(re-frisk/enable {:ignore-events #{::timer-db}})`
