### ISSUE TITLE
Hide re-frisk buttons & open debugging tools with shortcut key

### ISSUE THREAD

**Issue by Jarzka** [flexsurfer/re-frisk#68]
Hi

Is it possible to hide the re-frisk buttons that show on the UI and instead open the UI on the page with a special shortcut key? I find it difficult to use my app when re-frisk is running because its buttons are located on top of my app's UI elements.

For example, reframe-10x does not draw anything on the page unless you hit a special shortcut key (Ctrl + H). This way, the debugging tools are always easily availabe, but they do not disturb my UI if I don't need them.

**Comment by flexsurfer** [comment]
yes sure, PR are welcomed :)

**Comment by flexsurfer** [comment]
hey @Jarzka i don't want to hide UI by default, for new users, so will it work if we add a setting, and implement `[re-frisk.preload-hidden]` ? so if you want a hidden buttons you could use this preloader?

**Comment by Jarzka** [comment]
Sounds good to me 👍

**Comment by flexsurfer** [comment]
@Jarzka yes `ctrl+h`

**Comment by flexsurfer** [comment]
1.6.0
