### ISSUE TITLE
ignore-events from closure-defines

### ISSUE THREAD

**Issue by sirmspencer** [flexsurfer/re-frisk#74]
Basically this feature that already exists https://github.com/flexsurfer/re-frisk/issues/58, but configurable on clojure-defines.  

I am adding re-frisk to our app, but some devs still prefer re-frame-10x, which can only be added to via the shadow-cljs.edn :preloads.  It would be great to keep the configs for both there instead of requiring re-frisk from inside the app.

**Comment by sirmspencer** [comment]
Here is how re-frame implements it for the trace-enable? val that needs to be set to run this app. https://github.com/day8/re-frame/blob/master/src/re_frame/trace.cljc#L17

**Comment by flexsurfer** [comment]
yeah that would be a useful feature

**Comment by flexsurfer** [comment]
but I'm not sure what kind of data structures can be used in `:closure-defines` , there is only example for boolean

**Comment by flexsurfer** [comment]
also I'm not sure how namespaced keywords will work

**Comment by flexsurfer** [comment]
another option would be to ignore events in the UI and store them in the local storage

**Comment by flexsurfer** [comment]
another options would be to create your own preloader which will enable re-frisk with your options ,and use this preloader

**Comment by flexsurfer** [comment]
yeah i guess this is a solution

**Comment by sirmspencer** [comment]
Yes, that works great.  I have not spent too much time with preloaders yet so forgive my overlook.
