### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by sirmspencer** [flexsurfer/re-frisk#81]
Is this project deprecated?

**Comment by flexsurfer** [comment]
why?

**Comment by sirmspencer** [comment]
A year without updates.  I was just checking before opening bug tickets.

**Comment by flexsurfer** [comment]
PRs are very welcome :) also please tell me if there are any blockers for you

**Comment by ILoveHubGit** [comment]
reagent.dom/dom-node is deprecated. Sorry I can't find what function should be used instead of this one.
